---
development:
  #dialect: "sqlite3"
  #database: tmp/development.sqlite
  url: {{envOr "DATABASE_URL" "mysql://root:root@tcp(mysql:3306)/db_name?parseTime=true&multiStatements=true"}}

test:
  # url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/app_test?sslmode=disable"}}
  url: {{envOr "TEST_DATABASE_URL" "sqlite3:///app/tmp/test.sqlite?_fk=true"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@tcp(mysql:3306)/db_name?parseTime=true&multiStatements=true"}}
